//
//  TripConfigurator.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/2/15.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

typealias TripInteractorInput = TripViewControllerOutput
typealias TripPresenterInput = TripInteractorOutput
typealias TripPresenterOutput = TripViewControllerInput

class TripConfigurator
{
    // MARK: - Object lifecycle
    
    class var sharedInstance: TripConfigurator
    {
        struct Static {
            static var instance: TripConfigurator?
            static var token: dispatch_once_t = 0
        }
        
        dispatch_once(&Static.token) {
            Static.instance = TripConfigurator()
        }
        
        return Static.instance!
    }
    
    // MARK: - Configuration
    
    func configure(viewController: TripViewController)
    {
        let router = TripRouter()
        router.viewController = viewController
        
        let presenter = TripPresenter()
        presenter.output = viewController
        
        let interactor = TripInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
