//
//  TripInteractor.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/2/15.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

let TripInteractorErrorDomain = "TripInteractor"
enum TripInteractorError: ErrorType {
    case General
}

protocol TripInteractorOutput
{
    func presentTripDetail(response: Response<Trip_FetchTripDetail_Response>)
}

class TripInteractor: TripInteractorInput
{
    var output: TripInteractorOutput!
    var worker: TripWorker!

    // MARK: - Business logic
    func fetchTripDetail(request: Trip_FetchTripDetail_Request) -> () {
        PMIAPI.fetchJSON("trips/\(request.tripID).json", parameters: [:])
            .success { (responseData) -> Void in
                if let responseData = responseData as? [String: AnyObject] {
                    let response = Trip_FetchTripDetail_Response(tripData: responseData)
                    self.output.presentTripDetail(Response.Result(response))
                } else {
                    let error = NSError(domain: TripInteractorErrorDomain,
                        code: TripInteractorError.General)

                    self.output.presentTripDetail(Response.Error(error))
                }
            }.failure { (error, isCancelled) -> Void in
                if !isCancelled {
                    self.output.presentTripDetail(Response.Error(error!))
                }
            }
    }
}
