//
//  TripEditModels.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/3/13.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ObjectMapper

struct TripEditFormatModelRequest
{
}

struct TripEditFormatModelResponse
{
    var tripModel: [String: [PhotoGroup]]
}

class TripEditViewModel: MappableViewModel
{
    var title: String?
    var message: String?
    var locations: [TripLocationEditCellViewModel] = []

    typealias ViewModel = TripEditViewModel
    required init?(_ map: Map) {
    }
    func mapping(map: Map) -> () {
        title <- map["title"]
        message <- map["message"]

        if let photoGroups = map["photos"].currentValue as? [PhotoGroup] {
            for photoGroup in photoGroups {
                let locationViewModel = TripLocationEditCellViewModel()
                locationViewModel.title = ""
                locationViewModel.message = ""
                locationViewModel.city = photoGroup.city
                locationViewModel.street = photoGroup.street
                locationViewModel.location = photoGroup.location

                var albumPhotos: [PhotosFromAlbumPhotoViewModel] = [] ;
                for photo in photoGroup.photos {
                    albumPhotos.append(PhotosFromAlbumPhotoViewModel(photoData: photo))
                }
                locationViewModel.albumPhotos = albumPhotos

                locations.append(locationViewModel)
            }
        }
    }
}

class TripLocationEditCellViewModel: TripLocationCellViewModel {
    var title: String?
    var message: String?
    var albumPhotos: [PhotosFromAlbumPhotoViewModel] = []
}
