//
//  TripEditConfigurator.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/3/13.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
typealias TripEditInteractorInput = TripEditViewControllerOutput
typealias TripEditPresenterInput = TripEditInteractorOutput
typealias TripEditPresenterOutput = TripEditViewControllerInput

class TripEditConfigurator
{
    // MARK: - Object lifecycle
    class var sharedInstance: TripEditConfigurator
    {
        struct Static {
            static var instance: TripEditConfigurator?
            static var token: dispatch_once_t = 0
        }
        
        dispatch_once(&Static.token) {
            Static.instance = TripEditConfigurator()
        }
        
        return Static.instance!
    }
    
    // MARK: - Configuration
    func configure(viewController: TripEditViewController)
    {
        let router = TripEditRouter()
        router.viewController = viewController
        
        let presenter = TripEditPresenter()
        presenter.output = viewController
        
        let interactor = TripEditInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
