//
//  TripEditInteractor.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/3/13.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

enum TripEditInteractorError: ErrorType {
    case General
    case InvalidTripModel
}

protocol TripEditInteractorOutput
{
    func presentTripModel(response: Response<TripEditFormatModelResponse>)
}

class TripEditInteractor: TripEditInteractorInput
{
    var output: TripEditInteractorOutput!
    var worker: TripEditWorker!

    var tripModel: [String: [PhotoGroup]]?
    // MARK: - Business logic
    func formatModel(request: TripEditFormatModelRequest) {
        if let tripModel = tripModel {
            output.presentTripModel(Response.Result(TripEditFormatModelResponse(tripModel: tripModel)))
        } else {
            output.presentTripModel(Response.Error(NSError(errorType: TripEditInteractorError.InvalidTripModel)))
        }
    }
}