//
//  CameraModels.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/3/5.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Camera_LoadPhotosFromAlbum_Request {
}

struct Camera_LoadPhotosFromAlbum_Response {
    var photos: [String: Any]
}

struct PhotosFromAlbumViewModel {
    var sections: [PhotosFromAlbumSectionViewModel]!
    var photoViewModels: [[PhotosFromAlbumPhotoViewModel]]!

    static func viewModelFromDictonary(dictonary: [String: Any]) -> PhotosFromAlbumViewModel? {
        let groups = dictonary["groups"] as! [[String: Any]]
        var sections = [PhotosFromAlbumSectionViewModel]()
        var photoViewModelsArray = [[PhotosFromAlbumPhotoViewModel]]()
        for group in groups {
            let city = group["city"] as! String
            let street = group["street"] as! String
            let location = group["location"] as! String
            let date = group["date"] as? NSDate

            var dateString = ""
            if date != nil {
                let dateFormatter = NSDateFormatter()
                dateFormatter.dateFormat = "YYYY-MM-DD"
                dateString = dateFormatter.stringFromDate(date!)
            }

            var photoViewModels = [PhotosFromAlbumPhotoViewModel]()
            let photos = group["photos"] as! [[String: Any]]
            for photo in photos {
                photoViewModels.append(PhotosFromAlbumPhotoViewModel(asset: photo))
            }
            let sectionViewModel = PhotosFromAlbumSectionViewModel(
                location: location,
                street: street,
                city: city,
                date: dateString,
                photos: photoViewModels)
            photoViewModelsArray.append(photoViewModels)
            sections.append(sectionViewModel)
        }
        return PhotosFromAlbumViewModel(sections: sections, photoViewModels: photoViewModelsArray)
    }
}

class PhotosFromAlbumSectionViewModel {
    var location: String!
    var street: String!
    var city: String!
    var date: String!
    var photos: [PhotosFromAlbumPhotoViewModel]!

    init(location: String, street: String, city: String, date: String, photos: [PhotosFromAlbumPhotoViewModel]) {
        self.location = location
        self.street = street
        self.city = city
        self.date = date
        self.photos = photos
    }
}

class PhotosFromAlbumPhotoViewModel {
    var asset: Any!

    init(asset: Any) {
        self.asset = asset
    }
}