//
//  CameraModels.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/1/30.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CameraRequest
{
}

struct CameraResponse
{
}

struct CameraViewModel
{
}
