//
//  CameraPresenter.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/1/30.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CameraPresenterInput
{
    func presentSomething(response: CameraResponse)
}

protocol CameraPresenterOutput: class
{
    func displaySomething(viewModel: CameraViewModel)
}

class CameraPresenter: CameraPresenterInput
{
    weak var output: CameraPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentSomething(response: CameraResponse)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let viewModel = CameraViewModel()
        output.displaySomething(viewModel)
    }
}
