//
//  CameraInteractor.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/1/30.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CameraInteractorInput
{
    func doSomething(request: CameraRequest)
}

protocol CameraInteractorOutput
{
    func presentSomething(response: CameraResponse)
}

class CameraInteractor: CameraInteractorInput
{
    var output: CameraInteractorOutput!
    var worker: CameraWorker!
    
    // MARK: Business logic
    
    func doSomething(request: CameraRequest)
    {
        // NOTE: Create some Worker to do the work
        
        worker = CameraWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = CameraResponse()
        output.presentSomething(response)
    }
}
