//
//  PlantModels.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/1/31.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CoreLocation
import MapKit

struct PlantRequest
{
}

struct PlantResponse
{
}

struct PlantViewModel
{
}

// MARK: - FormatLocation
struct Plant_FormatLocation_Requset
{
    var location: CLLocation
}

struct Plant_FormatLocation_Response
{
    var information: [NSObject : AnyObject]
}

struct LocationViewModel
{
    var city: String?
    var street: String?
    var location: String?
}

// MARK: - FetchSightsData
struct Plant_FetchSightList_Request
{
    var region: MKCoordinateRegion;
}

struct Plant_FetchSightList_Response
{
    var sightList: [[String: AnyObject]]
}

struct SightListViewModel
{
    struct SightViewModel {
        var longitude: Double
        var latitude: Double
        var timestamp: UInt64
        var thumbnail: String?
        var sid: String?
        var uid: String?
        var imageCount: UInt
    }

    var sightList: [SightViewModel]
}
