//
//  PlantPresenter.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/1/31.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PlantPresenterInput
{
    func presentLocationInformation(response: Response<Plant_FormatLocation_Response, NSError>)
}

protocol PlantPresenterOutput: class
{
    func displayLocationInformation(viewModel: ViewModel<LocationViewModel, NSError>)
}

class PlantPresenter: PlantPresenterInput
{
    weak var output: PlantPresenterOutput!

    // MARK: Presentation logic
    func presentLocationInformation(response: Response<Plant_FormatLocation_Response, NSError>) {
        switch response {
        case .Error(let error):
            output.displayLocationInformation(ViewModel<LocationViewModel, NSError>.Error(error))
        case .Result(let result):
            let viewModel = LocationViewModel(
                city: result.information["City"] as? String
            , street: result.information["Street"] as? String
            , location: result.information["SubLocality"] as? String)

            output.displayLocationInformation(ViewModel<LocationViewModel, NSError>.Result(viewModel))
        }
    }
}
