//
//  TouristConfigurator.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/2/16.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
typealias TouristInteractorInput = TouristViewControllerOutput
typealias TouristPresenterInput = TouristInteractorOutput
typealias TouristPresenterOutput = TouristViewControllerInput

class TouristConfigurator
{
    // MARK: - Object lifecycle
    class var sharedInstance: TouristConfigurator
    {
        struct Static {
            static var instance: TouristConfigurator?
            static var token: dispatch_once_t = 0
        }
        
        dispatch_once(&Static.token) {
            Static.instance = TouristConfigurator()
        }
        
        return Static.instance!
    }
    
    // MARK: - Configuration
    func configure(viewController: TouristViewController)
    {
        let router = TouristRouter()
        router.viewController = viewController
        
        let presenter = TouristPresenter()
        presenter.output = viewController
        
        let interactor = TouristInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
