//
//  TouristInteractor.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/2/16.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

enum TouristInteractorError: ErrorType {
    case General
}

protocol TouristInteractorOutput
{
    func presentTouristDetail(response: Response<Tourist_FetchDetail_Response>)
}

class TouristInteractor: TouristInteractorInput
{
    var output: TouristInteractorOutput!
    var worker: TouristWorker!

    // MARK: - Business logic
    func fetchTouristDetail(request: Tourist_FetchDetail_Request) -> () {
        PMIAPI.fetchJSON("authors/\(request.touristID).json", parameters: [:])
            .success { (responseData) -> Void in
                if let responseData = responseData as? [String: AnyObject] {
                    let response = Tourist_FetchDetail_Response(detail: responseData)
                    self.output.presentTouristDetail(Response.Result(response))
                } else {
                    let error = NSError(errorType: TouristInteractorError.General)

                    self.output.presentTouristDetail(Response.Error(error))
                }
            }.failure { (error, isCancelled) -> Void in
                if !isCancelled {
                    self.output.presentTouristDetail(Response.Error(error!))
                }
            }
    }
}
