//
//  TouristViewController.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/2/16.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import PagingMenuController
import PKHUD

protocol TouristViewControllerInput: class
{
    func displayTouristDetail(viewModel: ViewModel<Tourist_FetchDetail_ViewModel>)
}

protocol TouristViewControllerOutput
{
    func fetchTouristDetail(request: Tourist_FetchDetail_Request)
}

class TouristViewController: PMIViewController, TouristViewControllerInput
{
    var output: TouristViewControllerOutput!
    var router: TouristRouter!

    internal var touristID = ""

    @IBOutlet weak var headView: TouristHeadView!

    var touristTripsViewController: TouristTripsViewController!
    var touristPhotosController: TouristPhotosController!
    var touristCollectionController: TouristCollectionController!
    var touristLocationsController: TouristCollectionController!

    // MARK: - Object lifecycle
    override func awakeFromNib()
    {
        super.awakeFromNib()
        TouristConfigurator.sharedInstance.configure(self)
    }

    // MARK: - View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()

        setupPagingMenuController()

        fetchTouristDetailOnLoad()
    }

    // MARK: - Event handling
    func fetchTouristDetailOnLoad()
    {
        let request = Tourist_FetchDetail_Request(touristID: touristID)
        output.fetchTouristDetail(request)
    }

    // MARK: - Display logic
    func displayTouristDetail(viewModel: ViewModel<Tourist_FetchDetail_ViewModel>)
    {
        switch viewModel {
        case .Error(let error):
            PKHUD.sharedHUD.contentView = PKHUDTextView(text: error.localizedDescription)
            PKHUD.sharedHUD.show()
            PKHUD.sharedHUD.hide(afterDelay: 2.0)
            break

        case .Result(let result):
            self.headView.viewModel = result
            touristTripsViewController.tripList = result.trips
            touristPhotosController.photoDateList = result.photoDateList
            touristPhotosController.photoList = result.photoList
            touristCollectionController.locationList = result.favLocationsList
            touristLocationsController.locationList = result.locationList
            break
        }
    }
}

extension TouristViewController {
    func setupPagingMenuController() {
        guard let storyboard = self.storyboard else { return }

        touristPhotosController = storyboard.instantiateViewControllerWithIdentifier("TouristPhotosController") as! TouristPhotosController
        touristTripsViewController = storyboard.instantiateViewControllerWithIdentifier("TouristTripsController") as! TouristTripsViewController
        touristCollectionController = storyboard.instantiateViewControllerWithIdentifier("TouristCollectionController") as! TouristCollectionController
        touristLocationsController = storyboard.instantiateViewControllerWithIdentifier("TouristLocationsController") as! TouristCollectionController
        //
        let viewControllers = [touristPhotosController,
            touristTripsViewController,
            touristCollectionController,
            touristLocationsController
        ]

        let pagingMenuController = self.childViewControllers.first as! PagingMenuController

        let options = PagingMenuOptions()

        options.menuHeight = 35
        options.backgroundColor = UIColor(hex: 0x2d3741)!
        options.selectedBackgroundColor = UIColor(hex: 0x414b55)!
        options.textColor = UIColor(hex: 0x9ba5af)!
        options.selectedTextColor = UIColor(hex: 0xd7e1eb)!
        options.font = UIFont.systemFontOfSize(8)
        options.selectedFont = UIFont.systemFontOfSize(8)
        options.menuDisplayMode = .SegmentedControl
        options.menuItemMode = .None;
        options.menuItems = [
            IconTextMenuItem(title: "99",
            icon: UIImage(named: "iconbutton_photoround")!,
            highlightedIcon: UIImage(named: "iconbutton_photoroundselect")!,
            spacing: 15),
            IconTextMenuItem(title: "99",
            icon: UIImage(named: "iconbutton_routeround")!,
            highlightedIcon: UIImage(named: "iconbutton_routeroundselect")!,
            spacing: 15),
            IconTextMenuItem(title: "99",
            icon: UIImage(named: "iconbutton_heartround")!,
            highlightedIcon: UIImage(named: "iconbutton_heartroundselect")!,
            spacing: 15),
            IconTextMenuItem(title: "99",
            icon: UIImage(named: "iconbutton_flaground")!,
            highlightedIcon: UIImage(named: "iconbutton_flagroundselect")!,
            spacing: 15),
        ]
        pagingMenuController.setup(viewControllers: viewControllers, options: options)
    }
}
