//
//  TouristPresenter.swift
//  PicMapIOS
//
//  Created by wangchaojs02 on 16/2/16.
//  Copyright (c) 2016年 wangchaojs02. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

enum TouristPresenterError: ErrorType {
    case General
}

class TouristPresenter: TouristPresenterInput
{
    weak var output: TouristPresenterOutput!

    // MARK: - Presentation logic
    func presentTouristDetail(response: Response<Tourist_FetchDetail_Response>)
    {
        switch response {
        case .Error(let error):
            output.displayTouristDetail(ViewModel.Error(error))
            break
        case .Result(let result):
            let viewModel = Tourist_FetchDetail_ViewModel.viewModelFromDictonary(result.detail)!
            output.displayTouristDetail(ViewModel.Result(viewModel))
            break
        }
    }
}
